### ISSUE TITLE
How would you write an integration test for Integrations.s.sol?

### ISSUE THREAD

**Issue by sharonphiliplima** [0xusmanf/decentralized-lottery-with-foundry#1]
Came across your repo and I am stuck on the problem:
There are three contracts - 
`import {CreateSubscription, FundSubscription, AddConsumer} from "../../script/Interactions.s.sol";
`
This is my soln to the `CreateSubscription`
```
function testCreateSubscriptionReturnsSubId() public {
        //Arrange
        CreateSubscription createSubscription = new CreateSubscription();
        uint64 testSubId = createSubscription.createSubscription(
            vrfCoordinator,
            deployerKey
        );
        //Act
        vm.recordLogs();
        VRFCoordinatorV2Mock(vrfCoordinator).createSubscription();
        Vm.Log[] memory entries = vm.getRecordedLogs();
        bytes32 subId = entries[0].topics[1];
        console.log("subId:", uint64(uint160(uint256(subId))));
        console.log("testSubId: ", testSubId);

        //Assert
        assert(testSubId == (uint64(uint160(uint256(subId))) - 1));
        //The mock gives the next subscriptionID! see the working below:
        //function createSubscription() external override returns (uint64 _subId) {
        //s_currentSubId++;
    }
```
Is that a valid approach?
Also, how do the test for the other two?
Thanks for your time.

**Comment by 0xusmanf** [comment]
Well while unit testing the first request to create  `testSubId` will always return 1 so there is no need to get the `subId` from `VRFCoordinatorV2Mock(vrfCoordinator).createSubscription();`. You can simply do this `assert(testSubId == 1));`. For the rest of 2, I haven't really worked on them so it will be better to ask someone who worked on those tests.

**Comment by sharonphiliplima** [comment]
Alright, thanks. 
Also, sir, would you be kind enough to guide me on how to conduct proper tests for the same repository's `DeployRaffle.s.sol?` I feel like I have run out of ideas.

**Comment by 0xusmanf** [comment]
Your main focus should be to increase coverage of `Raffle.sol` above 90% for now. It's alright if you can't think of any ideas for `DeployRaffle.s.sol`. But if you still want to try then 
1- write some tests to check if local variable values are appropriately updating according to the network.
2- Subscription ID is being created correctly.
2- Consumer is being added correctly etc.

**Comment by sharonphiliplima** [comment]
Yes, it is around 93% rn. 
Also, I have been trying to test the subId but I keep getting lost in the code flow.
